# Generated by Django 5.2.7 on 2026-04-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_remove_rental_posted_by_instructor_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='instructor',
        ),
        migrations.AddField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
            preserve_default=False,
        ),
    ]
