# Generated by Django 5.2.7 on 2026-04-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_reservation_instructor_reservation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='course',
            field=models.TextField(blank=True, null=True),
        ),
    ]
