# Generated by Django 5.2.7 on 2026-04-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='year_lvl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
