# Generated by Django 5.2.7 on 2026-04-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_year_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
