# Generated by Django 5.2.7 on 2026-04-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reservation_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
