# Generated by Django 5.2.7 on 2026-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservation_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserve_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_out',
            field=models.TextField(blank=True, null=True),
        ),
    ]
